import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import DarkModeToggle from "@/app/components/darkModeToggle"

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

const toggleDarkMode = () => {
  document.documentElement.classList.toggle('dark');
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center gap-4 
                            p-4 h-16 
                            bg-white 
                            dark:bg-gray-800">
           <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="px-4 sm:px-5 py-2 
                                   h-10 sm:h-12 
                                   bg-[#6c47ff] text-white 
                                   rounded-full font-medium 
                                   text-sm sm:text-base 
                                   cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
